spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

security:
  oauth2:
    client:
      client-id: simple-user
      client-secret: simple-user-secret
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
server:
  port: 5000


---

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/simple?useSSL=false&serverTimezone=Asia/Seoul&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20