server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false


simple:
  return_uri: http://localhost:8082/oauth/callback
